table trusted_nets {  }

listen on 0.0.0.0

queue ttl 4d
bounce warn-interval 1h, 6h, 2d
smtp max-message-size 35M

action "relay_mx" relay helo 

match from local for any action "relay_mx"
match from src <trusted_nets> for any action "relay_mx"
